"""empty message

Revision ID: 19b965bda369
Revises: 202a25e5c734
Create Date: 2016-09-22 18:11:30.426192

"""

# revision identifiers, used by Alembic.
revision = '19b965bda369'
down_revision = '202a25e5c734'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('name', sa.String()))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'name')
    ### end Alembic commands ###
