"""empty message

Revision ID: 33004fcae5f7
Revises: None
Create Date: 2016-09-11 16:11:16.583472

"""

# revision identifiers, used by Alembic.
revision = '33004fcae5f7'
down_revision = None

from alembic import op, context
import sqlalchemy as sa
from flask import current_app


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('student', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # MANUALLY ADDED the line below to grant permissions for the user found in config variable APP_SQL_USERNAME on table person.
    context.execute("GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE person TO " + current_app.config.get('APP_SQL_USERNAME'))
    context.execute("GRANT USAGE, SELECT ON SEQUENCE person_id_seq TO " + current_app.config.get('APP_SQL_USERNAME'))

    context.execute("GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE payment TO " + current_app.config.get('APP_SQL_USERNAME'))
    context.execute("GRANT USAGE, SELECT ON SEQUENCE payment_id_seq TO " + current_app.config.get('APP_SQL_USERNAME'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    op.drop_table('person')
    ### end Alembic commands ###
